basePath: /
definitions:
  responses.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  responses.HealthResponse:
    properties:
      errors:
        items:
          type: string
        type: array
      status:
        $ref: '#/definitions/responses.HealthStatus'
      timestamp:
        type: string
    type: object
  responses.HealthStatus:
    enum:
    - Healthy
    - Degraded
    type: string
    x-enum-varnames:
    - HealthStatusHealthy
    - HealthStatusDegraded
  responses.Outcome:
    enum:
    - VERIFIED
    - REJECTED
    type: string
    x-enum-varnames:
    - OutcomeVerified
    - OutcomeRejected
  responses.TokenResponse:
    properties:
      authToken:
        type: string
      clientId:
        type: string
      digitString:
        type: string
      expiryTime:
        type: integer
      message:
        type: string
      scanRef:
        type: string
      sessionLength:
        type: integer
      tokenType:
        type: string
    type: object
  responses.VerificationDataResponse:
    properties:
      additionalData: {}
      address:
        type: string
      addressVerification: {}
      ageEstimate:
        type: string
      authority:
        type: string
      birthPlace:
        type: string
      clientId:
        type: string
      clientIpProxyRiskLevel:
        type: string
      docBirthName:
        type: string
      docDateOfIssue:
        type: string
      docDob:
        type: string
      docExpiry:
        type: string
      docFirstName:
        type: string
      docIssuingCountry:
        type: string
      docLastName:
        type: string
      docNationality:
        type: string
      docNumber:
        type: string
      docPersonalCode:
        type: string
      docSex:
        type: string
      docTemporaryAddress:
        type: string
      docType:
        type: string
      driverLicenseCategory:
        type: string
      duplicateDocFaces:
        items:
          type: string
        type: array
      duplicateFaces:
        items:
          type: string
        type: array
      fullName:
        type: string
      idenfyRef:
        type: string
      manuallyDataChanged:
        type: boolean
      mothersMaidenName:
        type: string
      orgAddress:
        type: string
      orgAuthority:
        type: string
      orgBirthName:
        type: string
      orgBirthPlace:
        type: string
      orgFirstName:
        type: string
      orgLastName:
        type: string
      orgMothersMaidenName:
        type: string
      orgNationality:
        type: string
      orgTemporaryAddress:
        type: string
      selectedCountry:
        type: string
    type: object
  responses.VerificationStatusResponse:
    properties:
      clientId:
        type: string
      final:
        type: boolean
      idenfyRef:
        type: string
      status:
        $ref: '#/definitions/responses.Outcome'
    type: object
info:
  contact:
    email: info@codescalers.com
    name: Codescalers Egypt
    url: https://codescalers-egypt.com
  description: This is a KYC service for TFGrid.
  termsOfService: http://swagger.io/terms/
  title: TFGrid KYC API
  version: 0.1.0
paths:
  /api/v1/configs:
    get:
      description: Returns the app configs
      responses:
        "200":
          description: OK
          schema: {}
      summary: Get App Configs
      tags:
      - Misc
  /api/v1/data:
    get:
      consumes:
      - application/json
      description: Returns the verification data for a client
      parameters:
      - description: TFChain SS58Address
        in: header
        maxLength: 48
        minLength: 48
        name: X-Client-ID
        required: true
        type: string
      - description: hex-encoded message `{api-domain}:{timestamp}`
        in: header
        name: X-Challenge
        required: true
        type: string
      - description: hex-encoded sr25519|ed25519 signature
        in: header
        maxLength: 128
        minLength: 128
        name: X-Signature
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.VerificationDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get Verification Data
      tags:
      - Verification
  /api/v1/health:
    get:
      description: Returns the health status of the service
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.HealthResponse'
      summary: Health Check
      tags:
      - Health
  /api/v1/status:
    get:
      consumes:
      - application/json
      description: Returns the verification status for a client
      parameters:
      - description: TFChain SS58Address
        in: query
        maxLength: 48
        minLength: 48
        name: client_id
        type: string
      - description: Twin ID
        in: query
        minLength: 1
        name: twin_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.VerificationStatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get Verification Status
      tags:
      - Verification
  /api/v1/token:
    post:
      consumes:
      - application/json
      description: Returns a token for a client
      parameters:
      - description: TFChain SS58Address
        in: header
        maxLength: 48
        minLength: 48
        name: X-Client-ID
        required: true
        type: string
      - description: hex-encoded message `{api-domain}:{timestamp}`
        in: header
        name: X-Challenge
        required: true
        type: string
      - description: hex-encoded sr25519|ed25519 signature
        in: header
        maxLength: 128
        minLength: 128
        name: X-Signature
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Existing token retrieved
          schema:
            $ref: '#/definitions/responses.TokenResponse'
        "201":
          description: New token created
          schema:
            $ref: '#/definitions/responses.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "402":
          description: Payment Required
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get or Generate iDenfy Verification Token
      tags:
      - Token
  /api/v1/version:
    get:
      description: Returns the app version
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get App Version
      tags:
      - Misc
  /webhooks/idenfy/id-expiration:
    post:
      consumes:
      - application/json
      description: Processes the doc expiration notification for a client
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Process Doc Expiration Notification
      tags:
      - Webhooks
  /webhooks/idenfy/verification-update:
    post:
      consumes:
      - application/json
      description: Processes the verification update for a client
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Process Verification Update
      tags:
      - Webhooks
swagger: "2.0"
