version: '3.8'

services:
  tfgrid_kyc_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfgrid_kyc_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .app.env


  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .db.env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:

networks:
  default:
    name: tfgrid_kyc_network
    driver: bridge