version: '3.8'

services:
  tf_kyc_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf_kyc_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      tf_kyc_db:
        condition: service_healthy
    env_file:
      - .app.env


  tf_kyc_db:
    image: mongo:latest
    container_name: tf_kyc_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .db.env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
        - ME_CONFIG_MONGODB_SERVER=tf_kyc_db
        - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
        - tf_kyc_db
    ports:
      - "8888:8081"
    env_file:
      - .express.env

volumes:
  mongodb_data:

networks:
  default:
    name: tf_kyc_network
    driver: bridge